server {
    listen 80;
    server_name localhost;

    # Statische Angular Dateien ausliefern
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # API-Anfragen an das Backend weiterleiten
    location /api/ {
        # 'sun_backend' ist der Service-Name aus deiner docker-compose.yml
        proxy_pass http://sun_backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
