spring.application.name=SunService

# PostgreSQL Verbindung
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/sundb
spring.datasource.username=postgres
spring.datasource.password=Mnif4674!?

# JPA / Hibernate Einstellungen
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Zeigt die SQL-Befehle in der Konsole an
spring.jpa.show-sql=true

# CORS Einstellungen
app.cors.allowed-origins=http://localhost:4200,https://sauerburg.at,https://www.sauerburg.at,https://fotografie-nina.at,https://www.fotografie-nina.at

# Gmail SMTP Server Einstellungen
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.username=ferry.juraczka@gmail.com
spring.mail.password=${MAIL_PASSWORD}

# Sicherheits-Einstellungen
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

# Sagt Spring Boot, dass es hinter einem Proxy (Nginx) steht
server.forward-headers-strategy=native

# Falls du Cookies nutzt: Erlaubt das Speichern von Cookies \u00FCber HTTPS-Proxys
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true